peerServer:
  host: localhost
  port: 4444
  username: barbossa
  pingInterval: PT1M
  joinInterval: PT10S
  numPeers: 2
  failureCount: 3

bootstrap:
  host: localhost
  port: 55555
  msgSize: 65536
