app:
  file: 'app'
  level: TRACE
  enabled: true
  console: true

in:
  file: 'in'
  level: DEBUG
  enabled: true
  console: true

out:
  file: 'out'
  level: INFO
  enabled: true
  console: true

ping:
  file: 'ping'
  level: INFO
  enabled: true
  console: false